version: '3.8'

services:
  simunex-docs:
    image: simunex-docs:dev
    build:
      context: ../../../SimuNEX
      dockerfile: docs/sphinx/dev.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/docs
