version: '3.8'

services:
  doxygen-server:
    image: simunex-doxygen
    build:
      context: ../../SimuNEX
      dockerfile: docs/doxygen/Dockerfile
    volumes:
      - doxygen-html:/docs/html
    container_name: simunex-api

  sphinx-server:
    image: simunex-docs:latest
    build:
      context: ../../SimuNEX
      dockerfile: docs/sphinx/Dockerfile
    volumes:
      - sphinx-html:/docs/build/html

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - doxygen-html:/usr/share/nginx/html/docs/api
      - sphinx-html:/usr/share/nginx/html/docs/main
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - doxygen-server
      - sphinx-server

volumes:
  doxygen-html:
  sphinx-html: