# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory in the container to /docs
WORKDIR /docs

# Copy the requirements.txt file into the container at /docs
COPY requirements.txt /docs/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the content of the local docs directory to the container
COPY ./sphinx /docs

# Make port 8000 available outside this container
EXPOSE 8000

# Define environment variable
ENV NAME Documentation

# Run make html when the container launches
CMD ["make", "html"]
