version: '3.8'

services:
  simunex-docs:
    image: simunex-docs:dev
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./sphinx:/docs
    environment:
      - NAME=Documentation
