name: Release using conventional commits (main branch)

on:
  push:
   branches:
     - main

env:
  GH_TOKEN: ${{ secrets.SIMUNEX_ACTION }}

jobs:
  release:
   runs-on: ubuntu-latest

   steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
          token: ${{ env.GH_TOKEN }}
          persist-credentials: false

    - name: conventional changelog action
      id: changelog
      # https://github.com/TriPSs/conventional-changelog-action
      uses: TriPSs/conventional-changelog-action@latest
      with:
        # you can also create separate token to trace action
        github-token: "${{ env.GH_TOKEN }}"
        skip-on-empty: false

    - name: Build Documentation
      if: ${{ steps.changelog.outputs.skipped == 'false' }}
      run: |
        chmod +x ./build_docs.sh
        ./build_docs.sh

    - name: Commit and Push Changes
      if: ${{ steps.changelog.outputs.skipped == 'false' }}
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "Update documentation version [skip ci]"
        git push

    - name: create release
      # https://github.com/actions/create-release
      uses: softprops/action-gh-release@v1
      if: ${{steps.changelog.outputs.skipped == 'false'}}
      env:
        GITHUB_TOKEN: ${{ env.GH_TOKEN }}
      with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{steps.changelog.outputs.clean_changelog}}
          draft: false
          prerelease: false